#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/95af331e-a4ee-4612-9086-f4e9309455f5
  Arduino IoT Cloud Variables description
  The following variables are automatically generated and updated when changes are made to the Thing
  CloudLight led;
  CloudTemperatureSensor temperature;
  CloudRelativeHumidity humidity;
  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "DHT.h"
#include "thingProperties.h"
#include <ESP8266WiFi.h>

const char* ssid = "ssid";         // WiFi ağının SSID'si
const char* password = "password"; // WiFi ağının şifresi

#define DHTPIN D1
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);


void setup() {
  // WiFi ağına bağlanma
  Serial.println();
  Serial.println();
  Serial.print("WiFi ağına bağlanıyor: ");
  Serial.println(ssid);
  WiFi.begin(ssid, password);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi ağına bağlandı");
  Serial.println("IP Adresi: ");
  Serial.println(WiFi.localIP());


  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  pinMode(2, OUTPUT);
  delay(1500);
  dht.begin();
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}
void loop() {
  ArduinoCloud.update();
  DHT_SENSOR_READ();
  // Your code here
}

void onTemperatureChange() {
  // Sıcaklık değiştiğinde yapılacak işlemler buraya eklenir
}


void DHT_SENSOR_READ()
{
  float h = dht.readHumidity();
  float t = dht.readTemperature();

  temperature = t;
  humidity = h;

  Serial.print("Temperature - "); Serial.println(t);
  Serial.print("Humidity - "); Serial.println(h);
  delay(1000);
}
